name: Trigger home-assistant-ldap-ad build

on:
  workflow_dispatch:
  push:
    branches: [ "ad-dc-compatibility" ]

jobs:
  trigger_docker_build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger home-assistant-ldap-ad docker container build
      run: |
        curl -X POST https://api.github.com/repos/strnk/home-assistant-ldap-ad/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u ${{ secrets.WEBHOOK_TOKEN }} \
        --data '{"event_type": "trigger_buildimage "}'
